# Generated by Django 4.2.10 on 2024-08-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_available_course_price_group_max_users_count_and_more'),
        ('users', '0002_balance_bonuses_balance_user_customuser_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course', verbose_name='Курс'),
        ),
    ]
