# Generated by Django 4.2.10 on 2024-08-19 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_available_course_price_group_max_users_count_and_more'),
        ('users', '0003_alter_subscription_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.group', verbose_name='Группа'),
        ),
    ]
