# Generated by Django 4.2.10 on 2024-08-19 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Доступность'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0.0, max_length=250, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='group',
            name='max_users_count',
            field=models.IntegerField(default=30, verbose_name='Максимальное кол-во пользователей'),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='Новая группа', max_length=250, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
